Repository DoodleKing/Server, pull requests merged in 2025-01, with the labels that each got.

#1 [Scrum 14/Chore] 엔티티 매핑을 통한 스키마 구현
  src/main/java/mana/doodleking/domain/room/Room.java
  src/main/java/mana/doodleking/domain/room/RoomState.java
  src/main/java/mana/doodleking/domain/room/Subject.java
  src/main/java/mana/doodleking/domain/room/UserRoom.java
  src/main/java/mana/doodleking/domain/user/Character.java
  src/main/java/mana/doodleking/domain/user/User.java
  src/main/java/mana/doodleking/domain/user/UserState.java
Labels: chore

#4 [Scrum 9/Feat] ExceptionHandler 구현
  src/main/java/mana/doodleking/global/exception/DoodleKingExceptionHandler.java
Labels: feature

#7 [Scrum 9/Feat] ExceptionHandler, APIResponse 구현 및 유저 생성 로직 수정
  build.gradle
  src/main/java/mana/doodleking/domain/user/Character.java
  src/main/java/mana/doodleking/domain/user/User.java
  src/main/java/mana/doodleking/domain/user/controller/UserController.java
  src/main/java/mana/doodleking/domain/user/dto/CreateUserReq.java
  src/main/java/mana/doodleking/domain/user/dto/CreateUserRes.java
  src/main/java/mana/doodleking/domain/user/repository/CharacterRepository.java
  src/main/java/mana/doodleking/domain/user/repository/UserRepository.java
  src/main/java/mana/doodleking/domain/user/service/UserService.java
  src/main/java/mana/doodleking/global/exception/DoodleKingExceptionHandler.java
  src/main/java/mana/doodleking/global/response/APIResponse.java
  src/main/java/mana/doodleking/global/response/ResultCode.java
Labels: feature, refactor

#8 [Scrum 10/Feat] WebSocket을 활용하여 방 생성 시, 방 목록 조회
  src/main/java/mana/doodleking/domain/room/Room.java
  src/main/java/mana/doodleking/domain/room/RoomController.java
  src/main/java/mana/doodleking/domain/room/RoomRepository.java
  src/main/java/mana/doodleking/domain/room/RoomService.java
  src/main/java/mana/doodleking/domain/room/dto/PostRoomReq.java
  src/main/java/mana/doodleking/domain/room/dto/RoomDetail.java
  src/main/java/mana/doodleking/domain/room/dto/RoomSimple.java
  src/main/java/mana/doodleking/websocket/MessageType.java
  src/main/java/mana/doodleking/websocket/RequestChatContentsDto.java
  src/main/java/mana/doodleking/websocket/WebSocketConfig.java
Labels: feature

#10 [SCRUM-28/chore] cors 설정
  src/main/java/mana/doodleking/global/config/WebConfig.java
Labels: chore

#11 [SCRUM-10/Feat] createRoom 구현
  src/main/java/mana/doodleking/domain/room/Room.java
  src/main/java/mana/doodleking/domain/room/RoomController.java
  src/main/java/mana/doodleking/domain/room/RoomService.java
  src/main/java/mana/doodleking/domain/room/UserRoom.java
  src/main/java/mana/doodleking/domain/room/dto/PostRoomReq.java
  src/main/java/mana/doodleking/domain/room/dto/RoomDetail.java
  src/main/java/mana/doodleking/domain/room/dto/RoomSimple.java
  src/main/java/mana/doodleking/domain/room/enums/RoomState.java
  src/main/java/mana/doodleking/domain/room/enums/Subject.java
  src/main/java/mana/doodleking/domain/room/repository/RoomRepository.java
  src/main/java/mana/doodleking/domain/room/repository/UserRoomRepository.java
  src/main/java/mana/doodleking/domain/user/UserRole.java
  src/main/java/mana/doodleking/global/MessageSender.java
Labels: feature

#16 [Scrum 30/Chore]swagger 세팅
  build.gradle
  src/main/java/mana/doodleking/domain/room/RoomController.java
  src/main/java/mana/doodleking/domain/user/controller/UserController.java
  src/main/java/mana/doodleking/global/config/SwaggerConfig.java
  src/main/java/mana/doodleking/global/swagger/RoomControllerDocs.java
  src/main/java/mana/doodleking/global/swagger/UserControllerDocs.java
Labels: documentation

#18 [SCRUM-31/Refact] 인원이 모두 찬 경우 예외 처리 구현
  src/main/java/mana/doodleking/domain/room/RoomService.java
Labels: refactor

#20 [SCRUM-27/Feat] 사용자 준비 상태 변경
  src/main/java/mana/doodleking/domain/room/controller/RoomController.java
  src/main/java/mana/doodleking/domain/room/controller/UserRoomController.java
  src/main/java/mana/doodleking/domain/room/dto/UserStateDTO.java
  src/main/java/mana/doodleking/domain/room/service/RoomService.java
  src/main/java/mana/doodleking/domain/room/service/UserRoomService.java
  src/main/java/mana/doodleking/global/swagger/RoomControllerDocs.java
  src/main/java/mana/doodleking/global/swagger/UserRoomControllerDocs.java
Labels: feature
